# Generated by Django 5.2.7 on 2025-12-05 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('human_name', models.CharField(max_length=250, verbose_name='Название')),
                ('package_name', models.CharField(max_length=250, unique=True, verbose_name='Название пакета')),
            ],
            options={
                'verbose_name': 'Компонент',
                'verbose_name_plural': 'Компоненты',
                'db_table': 'component',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Название')),
                ('components', models.ManyToManyField(db_table='device_components', related_name='devices', to='updater.component', verbose_name='Компоненты')),
            ],
            options={
                'verbose_name': 'Устройство',
                'verbose_name_plural': 'Устройства',
                'db_table': 'device',
            },
        ),
        migrations.CreateModel(
            name='DistUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REQUESTED', 'Запрошено'), ('PROCESSING', 'В процессе применения'), ('ACTIVE', 'Активно'), ('ERROR', 'Ошибка применения'), ('PAST', 'В прошлом')], default='REQUESTED', max_length=50, verbose_name='Состояние')),
                ('task_id', models.UUIDField(null=True, verbose_name='ID задачи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='updater.device', verbose_name='Устройство')),
            ],
            options={
                'verbose_name': 'Задача выполнения dist-upgrade',
                'verbose_name_plural': 'Задачи выполнения dist-upgrade',
                'db_table': 'dist_upgrade',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=250, verbose_name='Номер версии')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='updater.component', verbose_name='Компонент')),
            ],
            options={
                'verbose_name': 'Версия',
                'verbose_name_plural': 'Версии',
                'db_table': 'version',
            },
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REQUESTED', 'Запрошено'), ('PROCESSING', 'В процессе применения'), ('ACTIVE', 'Активно'), ('ERROR', 'Ошибка применения'), ('PAST', 'В прошлом')], default='REQUESTED', max_length=50, verbose_name='Состояние')),
                ('task_id', models.UUIDField(null=True, verbose_name='ID задачи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='updater.device', verbose_name='Устройство')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='updater.version', verbose_name='Версия')),
            ],
            options={
                'verbose_name': 'Обновление',
                'verbose_name_plural': 'Обновления',
                'db_table': 'update',
            },
        ),
    ]
