# Generated by Django 5.2.7 on 2025-12-06 21:12

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Устройство',
                'verbose_name_plural': 'Устройства',
                'db_table': 'device',
            },
        ),
        migrations.CreateModel(
            name='DistUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REQUESTED', 'Запрошено'), ('PROCESSING', 'В процессе применения'), ('SUCCESS', 'Успешно применено'), ('ERROR', 'Ошибка применения')], default='REQUESTED', max_length=50, verbose_name='Состояние')),
                ('task_id', models.UUIDField(null=True, verbose_name='ID задачи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='updater.device', verbose_name='Устройство')),
            ],
            options={
                'verbose_name': 'Задача выполнения dist-upgrade',
                'verbose_name_plural': 'Задачи выполнения dist-upgrade',
                'db_table': 'dist_upgrade',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название пакета')),
                ('dependencies', models.ManyToManyField(blank=True, db_table='package_package_deps', related_name='dependant_packages', to='updater.package', verbose_name='Зависимости')),
            ],
            options={
                'verbose_name': 'Пакет',
                'verbose_name_plural': 'Пакеты',
                'db_table': 'package',
            },
        ),
        migrations.CreateModel(
            name='HistoricalConfigTemplate',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('file', models.TextField(max_length=100, verbose_name='Файл')),
                ('dest_path', models.CharField(help_text='Пример: /etc/nginx.conf)', max_length=255, verbose_name='Путь на устройстве')),
                ('file_mode', models.CharField(default='0644', max_length=4, verbose_name='Режим доступа к файлу')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Подставляются в шаблон', verbose_name='Параметры')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='updater.package', verbose_name='Пакет')),
            ],
            options={
                'verbose_name': 'История изменений шаблона конфига',
                'verbose_name_plural': 'Истории изменений шаблонов конфигов',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='DevicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied', models.BooleanField(default=False, verbose_name='Применено ли')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Подставляются в шаблон (имеют приоритет над параметрами в шаблоне)', verbose_name='Параметры')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_packages', to='updater.device', verbose_name='Устройство')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_packages', to='updater.package', verbose_name='Пакет')),
            ],
            options={
                'verbose_name': 'Связь устройства с пакетом',
                'verbose_name_plural': 'Связи устройств с пакетами',
                'db_table': 'device_package',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='packages',
            field=models.ManyToManyField(blank=True, related_name='devices', through='updater.DevicePackage', to='updater.package', verbose_name='Пакеты'),
        ),
        migrations.CreateModel(
            name='ConfigTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('file', models.FileField(upload_to='config_templates', verbose_name='Файл')),
                ('dest_path', models.CharField(help_text='Пример: /etc/nginx.conf)', max_length=255, verbose_name='Путь на устройстве')),
                ('file_mode', models.CharField(default='0644', max_length=4, verbose_name='Режим доступа к файлу')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Подставляются в шаблон', verbose_name='Параметры')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='updater.package', verbose_name='Пакет')),
            ],
            options={
                'verbose_name': 'Шаблон конфига',
                'verbose_name_plural': 'Шаблоны конфигов',
                'db_table': 'config_template',
            },
        ),
        migrations.CreateModel(
            name='PackageUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REQUESTED', 'Запрошено'), ('PROCESSING', 'В процессе применения'), ('SUCCESS', 'Успешно применено'), ('ERROR', 'Ошибка применения')], default='REQUESTED', max_length=50, verbose_name='Состояние')),
                ('task_id', models.UUIDField(null=True, verbose_name='ID задачи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='updater.device', verbose_name='Устройство')),
            ],
            options={
                'verbose_name': 'Обновление пакетов',
                'verbose_name_plural': 'Обновления пакетов',
                'db_table': 'component_update',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название сервиса в systemd (без .service)', max_length=250, unique=True, verbose_name='Название')),
                ('package_deps', models.ManyToManyField(blank=True, db_table='service_package_deps', related_name='services', to='updater.package', verbose_name='Пакеты-зависимости')),
                ('service_deps', models.ManyToManyField(blank=True, db_table='service_service_deps', related_name='dependant_services', to='updater.service', verbose_name='Сервисы-зависимости')),
            ],
            options={
                'verbose_name': 'Сервис',
                'verbose_name_plural': 'Сервисы',
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='HistoricalDeviceService',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('applied', models.BooleanField(default=False, verbose_name='Применено ли')),
                ('enabled', models.BooleanField(default=True, verbose_name='Включен ли')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('device', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='updater.device', verbose_name='Устройство')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='updater.service', verbose_name='Сервис')),
            ],
            options={
                'verbose_name': 'История изменений связей устройства с сервисом',
                'verbose_name_plural': 'Истории изменений связей устройств с сервисами',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='DeviceService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied', models.BooleanField(default=False, verbose_name='Применено ли')),
                ('enabled', models.BooleanField(default=True, verbose_name='Включен ли')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_services', to='updater.device', verbose_name='Устройство')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_services', to='updater.service', verbose_name='Сервис')),
            ],
            options={
                'verbose_name': 'Связь устройства с сервисом',
                'verbose_name_plural': 'Связи устройств с сервисами',
                'db_table': 'device_service',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='devices', through='updater.DeviceService', to='updater.service', verbose_name='Сервисы'),
        ),
        migrations.CreateModel(
            name='ServiceUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REQUESTED', 'Запрошено'), ('PROCESSING', 'В процессе применения'), ('SUCCESS', 'Успешно применено'), ('ERROR', 'Ошибка применения')], default='REQUESTED', max_length=50, verbose_name='Состояние')),
                ('task_id', models.UUIDField(null=True, verbose_name='ID задачи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='updater.device', verbose_name='Устройство')),
            ],
            options={
                'verbose_name': 'Обновление сервисов на устройстве',
                'verbose_name_plural': 'Обновления сервисов на устройствах',
                'db_table': 'service_update',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=250, verbose_name='Номер версии')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='updater.package', verbose_name='Пакет')),
            ],
            options={
                'verbose_name': 'Версия',
                'verbose_name_plural': 'Версии',
                'db_table': 'version',
            },
        ),
        migrations.CreateModel(
            name='HistoricalDevicePackage',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('applied', models.BooleanField(default=False, verbose_name='Применено ли')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Подставляются в шаблон (имеют приоритет над параметрами в шаблоне)', verbose_name='Параметры')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('device', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='updater.device', verbose_name='Устройство')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='updater.package', verbose_name='Пакет')),
                ('version', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='updater.version', verbose_name='Версия')),
            ],
            options={
                'verbose_name': 'История изменений связей устройства с пакетом',
                'verbose_name_plural': 'Истории изменений связей устройств с пакетами',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='devicepackage',
            name='version',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_packages', to='updater.version', verbose_name='Версия'),
        ),
        migrations.AddConstraint(
            model_name='deviceservice',
            constraint=models.UniqueConstraint(fields=('device_id', 'service_id'), name='unique_device_service'),
        ),
        migrations.AddConstraint(
            model_name='devicepackage',
            constraint=models.UniqueConstraint(fields=('device_id', 'package_id'), name='unique_device_package'),
        ),
    ]
