# Generated by Django 3.2.25 on 2025-12-10 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('updater', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='dependencies',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_deps',
        ),
        migrations.RemoveField(
            model_name='service',
            name='package_deps',
        ),
        migrations.AddField(
            model_name='device',
            name='antivirus_schedule',
            field=models.CharField(blank=True, help_text='Формат: * * * * * (м ч д м дн). Оставьте пустым, чтобы отключить.', max_length=100, null=True, verbose_name='Расписание обновления баз сигнатур антивируса'),
        ),
        migrations.AddField(
            model_name='device',
            name='next_run_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Время следующего запуска обновления антивируса'),
        ),
        migrations.CreateModel(
            name='ServiceServiceDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_deps_through', to='updater.service', verbose_name='Зависимый сервис')),
                ('dependency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependant_services_through', to='updater.service', verbose_name='Сервис-зависимость')),
            ],
            options={
                'verbose_name': 'Зависимость сервиса от сервиса',
                'verbose_name_plural': 'Зависимости сервисов от сервисов',
                'db_table': 'service_service_deps',
            },
        ),
        migrations.CreateModel(
            name='ServicePackageDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_deps_through', to='updater.service', verbose_name='Зависимый сервис')),
                ('dependency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependant_services_through', to='updater.package', verbose_name='Пакет-зависимость')),
                ('versions', models.ManyToManyField(blank=True, db_table='version_service_package_deps', related_name='services_package_deps', to='updater.Version', verbose_name='Версии')),
            ],
            options={
                'verbose_name': 'Зависимость сервиса от пакета',
                'verbose_name_plural': 'Зависимости сервисов от пакетов',
                'db_table': 'service_package_deps',
            },
        ),
        migrations.CreateModel(
            name='PackagePackageDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_deps_through', to='updater.package', verbose_name='Зависимый пакет')),
                ('dependency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependant_packages_through', to='updater.package', verbose_name='Пакет-зависимость')),
                ('versions', models.ManyToManyField(blank=True, related_name='package_package_deps', to='updater.Version', verbose_name='Версии')),
            ],
            options={
                'verbose_name': 'Зависимость пакета от пакета',
                'verbose_name_plural': 'Зависимости пакетов от пакетов',
                'db_table': 'package_package_deps',
            },
        ),
        migrations.CreateModel(
            name='HistoricalVersion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('number', models.CharField(max_length=250, verbose_name='Номер версии')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='updater.package', verbose_name='Пакет')),
            ],
            options={
                'verbose_name': 'История изменений версии',
                'verbose_name_plural': 'Истории изменений версий',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalService',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Название сервиса в systemd (без .service)', max_length=250, verbose_name='Название')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'История изменений сервиса',
                'verbose_name_plural': 'Истории изменений сервисов',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPackage',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название пакета')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'История изменений пакета',
                'verbose_name_plural': 'Истории изменений пакетов',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDevice',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250, verbose_name='Название')),
                ('is_available', models.BooleanField(blank=True, default=False, verbose_name='Доступность')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='Время последнего успешного пинга')),
                ('antivirus_schedule', models.CharField(blank=True, help_text='Формат: * * * * * (м ч д м дн). Оставьте пустым, чтобы отключить.', max_length=100, null=True, verbose_name='Расписание обновления баз сигнатур антивируса')),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Время следующего запуска обновления антивируса')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'История изменений устройства',
                'verbose_name_plural': 'Истории изменений устройств',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='AntivirusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REQUESTED', 'Запрошено'), ('PROCESSING', 'В процессе применения'), ('SUCCESS', 'Успешно применено'), ('ERROR', 'Ошибка применения')], default='REQUESTED', max_length=50, verbose_name='Состояние')),
                ('task_id', models.UUIDField(null=True, verbose_name='ID задачи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antivirusupdates', to='updater.device', verbose_name='Устройство')),
            ],
            options={
                'verbose_name': 'Обновление баз сигнатур антивируса на устройстве',
                'verbose_name_plural': 'Обновления баз сигнатур антивирусов на устройствах',
                'db_table': 'antivirus_update',
            },
        ),
        migrations.AddField(
            model_name='package',
            name='package_deps',
            field=models.ManyToManyField(blank=True, related_name='dependant_packages', through='updater.PackagePackageDependency', to='updater.Package', verbose_name='Зависимости'),
        ),
        migrations.AddField(
            model_name='service',
            name='package_deps',
            field=models.ManyToManyField(blank=True, related_name='dependant_services', through='updater.ServicePackageDependency', to='updater.Package', verbose_name='Пакеты-зависимости'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_deps',
            field=models.ManyToManyField(blank=True, related_name='dependant_services', through='updater.ServiceServiceDependency', to='updater.Service', verbose_name='Сервисы-зависимости'),
        ),
        migrations.AlterField(
            model_name='historicalpackage',
            name='name',
            field=models.CharField(db_index=True, max_length=250, verbose_name='Название пакета'),
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Название пакета'),
        ),
        migrations.AddConstraint(
            model_name='packagepackagedependency',
            constraint=models.UniqueConstraint(fields=('dependant', 'dependency'), name='unique_package_package_pair'),
        ),
        migrations.AddConstraint(
            model_name='servicepackagedependency',
            constraint=models.UniqueConstraint(fields=('dependant', 'dependency'), name='unique_service_package_pair'),
        ),
        migrations.AddConstraint(
            model_name='serviceservicedependency',
            constraint=models.UniqueConstraint(fields=('dependant', 'dependency'), name='unique_service_service_pair'),
        ),
    ]
