# Generated by Django 5.2.7 on 2025-12-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updater', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE MATERIALIZED VIEW target_state AS
            SELECT DISTINCT ON (d.id, v.component_id)
                (md5(d.name || '-' || c.package_name || '-' || v.number)::uuid) AS id,
                u.device_id AS device_id,
                v.component_id AS component_id,
                u.version_id AS version_id
            FROM update u
            JOIN device d ON u.device_id = d.id
            JOIN version v ON u.version_id = v.id
            JOIN device_components dc ON d.id = dc.device_id AND v.component_id = dc.component_id
            JOIN component c ON v.component_id = c.id
            WHERE u.status = 'REQUESTED'
            ORDER BY d.id, v.component_id, u.created_at DESC;

            CREATE UNIQUE INDEX idx_target_state_unique ON target_state (device_id, component_id);


            CREATE MATERIALIZED VIEW current_state AS
            SELECT DISTINCT ON (d.id, v.component_id)
                (md5(d.name || '-' || c.package_name || '-' || v.number)::uuid) AS id,
                d.id AS device_id,
                v.component_id AS component_id,
                u.version_id AS version_id
            FROM update u
            JOIN device d ON u.device_id = d.id
            JOIN version v ON u.version_id = v.id
            JOIN device_components dc ON d.id = dc.device_id AND v.component_id = dc.component_id
            JOIN component c ON v.component_id = c.id
            WHERE u.status = 'APPLIED'
            ORDER BY d.id, v.component_id, u.created_at DESC;

            CREATE UNIQUE INDEX idx_current_state_unique ON current_state (device_id, component_id);
            
            
            CREATE OR REPLACE FUNCTION refresh_state_views()
            RETURNS TRIGGER LANGUAGE plpgsql AS $$
            BEGIN
                REFRESH MATERIALIZED VIEW CONCURRENTLY target_state;
                REFRESH MATERIALIZED VIEW CONCURRENTLY current_state;
                RETURN NULL;
            END;
            $$;

            CREATE TRIGGER trigger_update_refresh
            AFTER INSERT OR UPDATE OR DELETE ON update
            FOR EACH STATEMENT
            EXECUTE FUNCTION refresh_state_views();

            CREATE TRIGGER trigger_device_components_refresh
            AFTER INSERT OR UPDATE OR DELETE ON device_components
            FOR EACH STATEMENT
            EXECUTE FUNCTION refresh_state_views();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS trigger_update_refresh ON "update";
            DROP TRIGGER IF EXISTS trigger_device_components_refresh ON device_components;

            DROP FUNCTION IF EXISTS refresh_state_views();

            DROP MATERIALIZED VIEW IF EXISTS current_state;
            DROP MATERIALIZED VIEW IF EXISTS target_state;
            """,
        ),
        migrations.CreateModel(
            name='CurrentState',
            fields=[
                ('id', models.UUIDField(db_column='id', primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'current_state',
                'managed': False,
                'verbose_name': 'Текущее состояние',
                'verbose_name_plural': 'Текущее состояние',
            },
        ),
        migrations.CreateModel(
            name='TargetState',
            fields=[
                ('id', models.UUIDField(db_column='id', primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'target_state',
                'managed': False,
                'verbose_name': 'Целевое состояние',
                'verbose_name_plural': 'Целевое состояние',
            },
        ),
    ]
