# Generated by Django 3.2.25 on 2025-12-27 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('updater', '0002_versioned_deps_and_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='package_deps',
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='package',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='updater.package', verbose_name='Пакет'),
        ),
        migrations.AddField(
            model_name='service',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='updater.package', verbose_name='Пакет'),
        ),
        migrations.DeleteModel(
            name='ServicePackageDependency',
        ),
    ]
